/** `web/src/subapps/<webModuleId>/index.tsx` — the page, default-exporting
 * a `SubAppModule`.
 *
 * ── WHY THE PAGE IS DATA-DRIVEN ──────────────────────────────────────
 * The obvious emitter unrolls one bespoke component per route and produces
 * a file that grows linearly in ugliness with the spec. This one emits a
 * `PANELS` constant — the spec, as data — plus a fixed renderer that is the
 * same text in every generated app. Two payoffs: the emitted file stays
 * reviewable at any spec size, and the part that could contain a bug is
 * written once here rather than re-synthesised per app.
 *
 * ── TWO DELIBERATE DEPARTURES FROM `shell-reference/index.tsx` ───────
 * 1. It calls `fetch` through a local helper instead of the host's `api`
 *    client. Adding a method to `web/src/api.ts` is an edit to a HOST file,
 *    and this generator emits exactly two host edits: the sub-app's own
 *    directories and the registry patch. A page that quietly required a
 *    third would be a page that does not actually drop in.
 * 2. Its strings are literal English, not `t()` keys — and this one is
 *    forced, not preferred. `import.meta.glob` covers the web MODULE but
 *    not i18n: a dictionary needs a hand-written static import plus a
 *    spread in `web/src/i18n.ts`, AND an update to the frozen key counts
 *    in `tests/subapps/i18nSplit.test.ts`, which assert EXACT totals
 *    (`TOTAL_KEYS = 4071`, not `toBeGreaterThan`). A generated sub-app
 *    shipping one i18n key turns a host test red until a human edits two
 *    more files. The contract's own reading: emit the count delta, or emit
 *    no i18n at all. This emitter emits none, which is why `registry.ts`
 *    stays the ONLY host edit codegen asks for — and why `shell-reference`,
 *    the documented floor, ships no dictionary either.
 *    ⚠ KNOWN GAP, stated rather than hidden: a generated page is therefore
 *    English-only, and the emitted header says so in the file itself.
 * 3. It ships NO stylesheet. `web/src/subapps` contains zero `.css` files;
 *    every sub-app's CSS lives in a banner-delimited region of the shared
 *    `web/src/theme.css`, and `tests/keyboardOperability.test.tsx` reads
 *    only that file. So this page uses the existing class names
 *    (`page`, `card`, `muted`, `mono`, `errorbox`, `okbox`) and adds none.
 *
 * Refusals are routed on STATUS and the body's `code`, never on prose —
 * the discipline `shell-reference/index.tsx` sets, kept here because it is
 * the difference between a page that explains a 403 and one that shows a
 * server sentence to a person who cannot act on it. */
import { banner, joinLines, str } from "../emit";
import type { PlannedDomain, PlannedRoute, SubAppPlan } from "../plan";

interface FieldDescriptor {
  name: string;
  label: string;
  control: "text" | "number" | "checkbox" | "select";
  options: string[] | null;
  optional: boolean;
}

export function emitWebModule(plan: SubAppPlan): string {
  const panels = plan.domains.map((domain) => panelLiteral(plan, domain));
  return joinLines([
    banner([
      `${plan.label} — GENERATED page. Default-exports a \`SubAppModule\`; the web loader globs this exact path (\`web/src/subapps/${plan.webModuleId}/index.tsx\`) and lazy-mounts \`.Page\`.`,
      "",
      "Every panel below is derived from the spec. The renderer under it is fixed text, identical in every generated sub-app.",
      "",
      "⚠ English-only, deliberately. A dictionary would need a static import and a spread in `web/src/i18n.ts` AND an update to the EXACT frozen key counts in `tests/subapps/i18nSplit.test.ts` — so shipping one i18n key turns a host test red. Emitting none is what keeps `registry.ts` the only host edit this sub-app asks for.",
      "No stylesheet ships with this page: sub-app CSS lives in a banner-delimited region of the shared `web/src/theme.css`. The class names below are the existing ones.",
      "",
      "Refusals are routed on the HTTP status and the body's `code` — never on the server's prose, which is developer-facing English and must not land inside a translated sentence later.",
    ]),
    `import { useCallback, useEffect, useState, type FormEvent } from "react";`,
    `import type { SubAppModule } from "../registry";`,
    "",
    `const ROUTE_PREFIX = ${str(plan.routePrefix)};`,
    `const APP_TITLE = ${str(plan.label)};`,
    `const APP_BLURB = ${str(plan.summary ?? `${plan.label} — generated by Flightdeck Studio.`)};`,
    "",
    RUNTIME_TYPES,
    "",
    "const PANELS: PanelDescriptor[] = [",
    panels.join("\n"),
    "];",
    "",
    RUNTIME,
    "",
    "const subAppModule: SubAppModule = { Page: GeneratedPage };",
    "export default subAppModule;",
    "",
  ]);
}

function panelLiteral(plan: SubAppPlan, domain: PlannedDomain): string {
  const list = domain.routes.find((r) => r.method === "GET");
  const forms = domain.routes.filter((r) => r.bodyConstName !== null);
  const parts: string[] = [
    "  {",
    `    id: ${str(domain.name)},`,
    `    title: ${str(domain.title)},`,
    list === undefined
      ? "    list: null,"
      : `    list: { path: ${str(subPathFor(plan, list))}, label: ${str(list.summary ?? `Load ${domain.title.toLowerCase()}`)} },`,
    "    forms: [",
  ];
  for (const form of forms) {
    parts.push(
      "      {",
      `        id: ${str(`${form.fastifyMethod}-${form.subPath}`)},`,
      `        method: ${str(form.method)},`,
      `        path: ${str(subPathFor(plan, form))},`,
      `        label: ${str(form.summary ?? `${form.method} ${form.subPath}`)},`,
      `        fields: [${fieldDescriptors(form).map(fieldLiteral).join(", ")}],`,
      "      },",
    );
  }
  parts.push("    ],", "  },");
  return parts.join("\n");
}

/** The page fetches `ROUTE_PREFIX + subPath`, so the emitted descriptor
 * carries the sub-path only — one place for the prefix, on both sides. */
function subPathFor(plan: SubAppPlan, route: PlannedRoute): string {
  return route.fullPath.slice(plan.routePrefix.length);
}

function fieldDescriptors(route: PlannedRoute): FieldDescriptor[] {
  return route.fields.map((field) => ({
    name: field.name,
    label: humanize(field.name),
    control: field.type === "boolean" ? "checkbox" : field.type === "enum" ? "select" : field.type === "string" ? "text" : "number",
    options: field.type === "enum" ? [...(field.values ?? [])] : null,
    optional: field.optional === true,
  }));
}

function fieldLiteral(field: FieldDescriptor): string {
  const options = field.options === null ? "null" : `[${field.options.map(str).join(", ")}]`;
  return `{ name: ${str(field.name)}, label: ${str(field.label)}, control: ${str(field.control)}, options: ${options}, optional: ${String(field.optional)} }`;
}

function humanize(camel: string): string {
  const spaced = camel.replace(/([a-z0-9])([A-Z])/g, "$1 $2");
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

const RUNTIME_TYPES = `interface FieldDescriptor {
  name: string;
  label: string;
  control: "text" | "number" | "checkbox" | "select";
  options: string[] | null;
  optional: boolean;
}

interface FormDescriptor {
  id: string;
  method: string;
  path: string;
  label: string;
  fields: FieldDescriptor[];
}

interface PanelDescriptor {
  id: string;
  title: string;
  list: { path: string; label: string } | null;
  forms: FormDescriptor[];
}

interface Refusal {
  status: number | null;
  code: string | null;
  scope: string | null;
  detail: string;
}`;

const RUNTIME = `class ApiRefusal extends Error {
  constructor(readonly refusal: Refusal) {
    super(refusal.detail);
  }
}

async function call(method: string, path: string, body?: unknown): Promise<unknown> {
  let res: Response;
  try {
    res = await fetch(ROUTE_PREFIX + path, {
      method,
      credentials: "same-origin",
      headers: body === undefined ? undefined : { "content-type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
  } catch (err) {
    throw new ApiRefusal({ status: null, code: null, scope: null, detail: (err as Error).message });
  }
  const text = await res.text();
  let parsed: Record<string, unknown> | null = null;
  try {
    parsed = text.length > 0 ? (JSON.parse(text) as Record<string, unknown>) : null;
  } catch {
    parsed = null;
  }
  if (!res.ok) {
    const issues = Array.isArray(parsed?.issues)
      ? (parsed.issues as Array<{ message?: string }>).map((i) => i.message ?? "").filter((m) => m.length > 0).join("; ")
      : "";
    throw new ApiRefusal({
      status: res.status,
      code: typeof parsed?.code === "string" ? parsed.code : null,
      scope: typeof parsed?.scope === "string" ? parsed.scope : null,
      detail: issues.length > 0 ? issues : typeof parsed?.error === "string" ? parsed.error : text.slice(0, 300),
    });
  }
  return parsed;
}

/** One sentence per REAL condition a generated route can answer. Routed on
 * the status and the body's code — never on the server's prose. */
function refusalText(r: Refusal): string {
  if (r.status === 400) return "The server refused this input.";
  if (r.status === 403 && r.code === "subapp_disabled") return "This app is not enabled for this workspace.";
  if (r.status === 403 && r.code === "capability_denied") {
    return "This app's access to " + (r.scope ?? "a capability") + " is not granted here.";
  }
  if (r.status === 403) return "Your role may not use this app.";
  if (r.status === 404) return "That record is not here any more — reload.";
  if (r.status === null) return "The server could not be reached.";
  return "The server answered " + String(r.status) + ".";
}

function RefusalBox({ refusal }: { refusal: Refusal }) {
  return (
    <div className="errorbox" role="alert" data-status={refusal.status ?? "network"} data-code={refusal.code ?? ""}>
      {refusalText(refusal)} {refusal.detail.length > 0 && <code className="mono">{refusal.detail}</code>}
    </div>
  );
}

function asRows(payload: unknown): Array<Record<string, unknown>> {
  if (Array.isArray(payload)) return payload as Array<Record<string, unknown>>;
  const rows = (payload as { rows?: unknown } | null)?.rows;
  return Array.isArray(rows) ? (rows as Array<Record<string, unknown>>) : [];
}

function cellText(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

function RowTable({ rows }: { rows: Array<Record<string, unknown>> }) {
  if (rows.length === 0) return <p className="muted">Nothing here yet.</p>;
  const columns = Object.keys(rows[0] ?? {});
  return (
    <table>
      <thead>
        <tr>
          {columns.map((column) => (
            <th key={column}>{column}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, index) => (
          <tr key={cellText(row.id) || String(index)}>
            {columns.map((column) => (
              <td key={column} className="mono">
                {cellText(row[column])}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function RouteForm({ form, onDone }: { form: FormDescriptor; onDone: () => void }) {
  const [values, setValues] = useState<Record<string, string | boolean>>({});
  const [busy, setBusy] = useState(false);
  const [refusal, setRefusal] = useState<Refusal | null>(null);
  const [ok, setOk] = useState<string | null>(null);

  async function submit(event: FormEvent) {
    event.preventDefault();
    if (busy) return;
    setBusy(true);
    setRefusal(null);
    setOk(null);
    const body: Record<string, unknown> = {};
    for (const field of form.fields) {
      const raw = values[field.name];
      if (field.control === "checkbox") {
        body[field.name] = raw === true;
        continue;
      }
      const text = typeof raw === "string" ? raw.trim() : "";
      if (text.length === 0) {
        if (!field.optional) body[field.name] = "";
        continue;
      }
      body[field.name] = field.control === "number" ? Number(text) : text;
    }
    try {
      const answer = await call(form.method, form.path, body);
      setOk(JSON.stringify(answer));
      setValues({});
      onDone();
    } catch (err) {
      setRefusal(err instanceof ApiRefusal ? err.refusal : { status: null, code: null, scope: null, detail: String(err) });
    } finally {
      setBusy(false);
    }
  }

  return (
    <form onSubmit={submit} data-form={form.id}>
      <h4>{form.label}</h4>
      {form.fields.map((field) => (
        <label key={field.name}>
          <span>
            {field.label}
            {field.optional ? " (optional)" : ""}
          </span>
          {field.control === "checkbox" ? (
            <input
              type="checkbox"
              checked={values[field.name] === true}
              onChange={(e) => setValues((v) => ({ ...v, [field.name]: e.target.checked }))}
            />
          ) : field.control === "select" ? (
            <select
              value={typeof values[field.name] === "string" ? (values[field.name] as string) : ""}
              onChange={(e) => setValues((v) => ({ ...v, [field.name]: e.target.value }))}
            >
              <option value="">—</option>
              {(field.options ?? []).map((option) => (
                <option key={option} value={option}>
                  {option}
                </option>
              ))}
            </select>
          ) : (
            <input
              type={field.control === "number" ? "number" : "text"}
              value={typeof values[field.name] === "string" ? (values[field.name] as string) : ""}
              onChange={(e) => setValues((v) => ({ ...v, [field.name]: e.target.value }))}
            />
          )}
        </label>
      ))}
      <button type="submit" disabled={busy} aria-busy={busy}>
        {busy ? "Working…" : "Submit"}
      </button>
      {refusal && <RefusalBox refusal={refusal} />}
      {ok && (
        <div className="okbox" role="status">
          <code className="mono">{ok}</code>
        </div>
      )}
    </form>
  );
}

function Panel({ panel }: { panel: PanelDescriptor }) {
  const [rows, setRows] = useState<Array<Record<string, unknown>> | null>(null);
  const [refusal, setRefusal] = useState<Refusal | null>(null);
  const listPath = panel.list?.path ?? null;

  const load = useCallback(async () => {
    if (listPath === null) return;
    setRefusal(null);
    try {
      setRows(asRows(await call("GET", listPath)));
    } catch (err) {
      setRows(null);
      setRefusal(err instanceof ApiRefusal ? err.refusal : { status: null, code: null, scope: null, detail: String(err) });
    }
  }, [listPath]);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <section className="card" data-panel={panel.id}>
      <h3>{panel.title}</h3>
      {refusal && <RefusalBox refusal={refusal} />}
      {listPath !== null && !refusal && rows === null && <p className="muted">Loading…</p>}
      {rows !== null && <RowTable rows={rows} />}
      {panel.forms.map((form) => (
        <RouteForm key={form.id} form={form} onDone={() => void load()} />
      ))}
    </section>
  );
}

function GeneratedPage() {
  return (
    <div className="page">
      <h2>{APP_TITLE}</h2>
      <p className="muted">{APP_BLURB}</p>
      {PANELS.map((panel) => (
        <Panel key={panel.id} panel={panel} />
      ))}
    </div>
  );
}`;
