/** The `registry.ts` edit, as a patch.
 *
 * A sub-app is code-declared, not installed: `SUBAPP_MANIFESTS` is a
 * hand-maintained array, and "adding a sub-app is exactly as heavy as
 * adding a route file: import + push — never a directory scan or
 * hot-install path (explicitly out of scope, APP-F02)". So the last thing
 * codegen produces is not a file it owns; it is an edit to a file the host
 * owns, and the honest form of that is a patch a human reads before
 * applying.
 *
 * ── THREE PROPERTIES THIS PATCH HAS ──────────────────────────────────
 * 1. IDEMPOTENT. Applying it to a registry that already imports this
 *    sub-app is a no-op that reports `already-applied`, not a second import
 *    and a duplicate array entry. Regenerating is the normal case.
 * 2. ANCHORED, NOT POSITIONAL. It finds the last manifest import and the
 *    array's closing bracket. A registry that has grown two sub-apps since
 *    the spec was written still patches cleanly; a line number would not.
 * 3. FAIL-LOUD. If an anchor is missing — someone reshaped the registry —
 *    it throws and names what it looked for. It never guesses a location,
 *    because a wrong guess produces a file that does not compile in
 *    somebody else's repository.
 *
 * The unified diff is generated from the SAME insertion plan `apply()`
 * uses, so the diff a reviewer reads and the edit the tool makes cannot
 * disagree. `__tests__/registry-patch.test.ts` pins that by applying the
 * emitted diff with `git apply` semantics of its own and comparing. */
import type { SubAppPlan } from "./plan";

export const REGISTRY_PATH = "server/subapps/registry.ts";

export class RegistryPatchError extends Error {}

export interface RegistryInsertion {
  /** Index in the ORIGINAL line array; the lines go before this line. */
  at: number;
  lines: string[];
  reason: string;
}

export interface RegistryPatchPlan {
  insertions: RegistryInsertion[];
  alreadyApplied: boolean;
}

export interface RegistryPatch {
  /** Repo-relative path of the file this patch edits. */
  file: string;
  /** The `import { xManifest } from "./x/manifest.js";` line. */
  importLine: string;
  /** The lines pushed into SUBAPP_MANIFESTS (a comment plus the entry). */
  entryLines: string[];
  /** Where the two edits land in `source`, and whether they are already there. */
  plan(source: string): RegistryPatchPlan;
  /** The patched file. `status` is `already-applied` when nothing changed. */
  apply(source: string): { source: string; status: "applied" | "already-applied" };
  /** A unified diff of `apply(source)`, with three lines of context. */
  toUnifiedDiff(source: string): string;
}

const MANIFEST_IMPORT_RE = /^import\s+\{[^}]*\}\s+from\s+"\.\/[a-z0-9-]+\/manifest\.js";\s*$/;
const TYPES_IMPORT_RE = /from\s+"\.\/types\.js";\s*$/;
const ARRAY_OPEN_RE = /^export\s+const\s+SUBAPP_MANIFESTS\s*:\s*SubAppManifest\[\]\s*=\s*\[\s*$/;

export function buildRegistryPatch(plan: SubAppPlan): RegistryPatch {
  const importLine = `import { ${plan.names.manifestConst} } from "./${plan.id}/manifest.js";`;
  const entryLines = [
    `  // Generated by Flightdeck Studio. Kill switch: ${plan.envVar}`,
    `  ${plan.names.manifestConst},`,
  ];
  const importMarker = `"./${plan.id}/manifest.js"`;

  function planPatch(source: string): RegistryPatchPlan {
    const lines = splitLines(source);
    if (lines.some((line) => line.includes(importMarker))) {
      return { insertions: [], alreadyApplied: true };
    }

    const importAt = findImportAnchor(lines);
    const entryAt = findArrayCloseAnchor(lines, plan.id);
    // Ascending by `at`; the import anchor always precedes the array.
    return {
      insertions: [
        { at: importAt, lines: [importLine], reason: "import the generated manifest" },
        { at: entryAt, lines: entryLines, reason: "push it into SUBAPP_MANIFESTS" },
      ],
      alreadyApplied: false,
    };
  }

  return {
    file: REGISTRY_PATH,
    importLine,
    entryLines,
    plan: planPatch,
    apply(source: string) {
      const patch = planPatch(source);
      if (patch.alreadyApplied) return { source, status: "already-applied" };
      const lines = splitLines(source);
      const out: string[] = [];
      for (let i = 0; i <= lines.length; i++) {
        for (const insertion of patch.insertions) {
          if (insertion.at === i) out.push(...insertion.lines);
        }
        if (i < lines.length) out.push(lines[i] as string);
      }
      return { source: out.join("\n") + (source.endsWith("\n") ? "\n" : ""), status: "applied" };
    },
    toUnifiedDiff(source: string) {
      const patch = planPatch(source);
      if (patch.alreadyApplied) return "";
      return formatUnifiedDiff(REGISTRY_PATH, splitLines(source), patch.insertions);
    },
  };
}

function splitLines(source: string): string[] {
  const lines = source.split("\n");
  // A trailing newline yields a final empty element that is not a line.
  if (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return lines;
}

/** After the LAST existing `./<x>/manifest.js` import, so generated entries
 * accumulate in one block; failing that, after the `./types.js` import,
 * which every registry has because `subAppManifestSchema` lives there. */
function findImportAnchor(lines: readonly string[]): number {
  for (let i = lines.length - 1; i >= 0; i--) {
    if (MANIFEST_IMPORT_RE.test(lines[i] as string)) return i + 1;
  }
  for (let i = lines.length - 1; i >= 0; i--) {
    const line = lines[i] as string;
    if (line.startsWith("import ") && TYPES_IMPORT_RE.test(line)) return i + 1;
  }
  throw new RegistryPatchError(
    `${REGISTRY_PATH}: found no manifest import and no "./types.js" import to anchor the new import to — refusing to guess a location`,
  );
}

/** The line holding the array's closing `];`, found by scanning forward
 * from the declaration rather than by matching brackets anywhere in the
 * file: a `];` inside an earlier statement must not be mistaken for it. */
function findArrayCloseAnchor(lines: readonly string[], id: string): number {
  const open = lines.findIndex((line) => ARRAY_OPEN_RE.test(line));
  if (open === -1) {
    throw new RegistryPatchError(
      `${REGISTRY_PATH}: no "export const SUBAPP_MANIFESTS: SubAppManifest[] = [" declaration — cannot push "${id}" into an array that is not there`,
    );
  }
  for (let i = open + 1; i < lines.length; i++) {
    if ((lines[i] as string).trim() === "];") return i;
  }
  throw new RegistryPatchError(`${REGISTRY_PATH}: SUBAPP_MANIFESTS is opened at line ${open + 1} but never closed with "];"`);
}

const CONTEXT = 3;

interface Hunk {
  start: number;
  end: number;
  insertions: RegistryInsertion[];
}

/** Insertion-only unified diff. Insertion-only is why this is short and
 * exact rather than an LCS implementation with an off-by-one in it: the
 * only thing that ever changes is which lines are added and where. */
export function formatUnifiedDiff(path: string, lines: readonly string[], insertions: readonly RegistryInsertion[]): string {
  if (insertions.length === 0) return "";
  const sorted = [...insertions].sort((a, b) => a.at - b.at);

  const hunks: Hunk[] = [];
  for (const insertion of sorted) {
    const start = Math.max(0, insertion.at - CONTEXT);
    const end = Math.min(lines.length, insertion.at + CONTEXT);
    const last = hunks[hunks.length - 1];
    if (last !== undefined && start <= last.end) {
      last.end = Math.max(last.end, end);
      last.insertions.push(insertion);
      continue;
    }
    hunks.push({ start, end, insertions: [insertion] });
  }

  const out: string[] = [`--- a/${path}`, `+++ b/${path}`];
  let offset = 0;
  for (const hunk of hunks) {
    const added = hunk.insertions.reduce((n, i) => n + i.lines.length, 0);
    const oldCount = hunk.end - hunk.start;
    out.push(`@@ -${hunk.start + 1},${oldCount} +${hunk.start + 1 + offset},${oldCount + added} @@`);
    for (let i = hunk.start; i < hunk.end; i++) {
      for (const insertion of hunk.insertions) {
        if (insertion.at === i) for (const line of insertion.lines) out.push(`+${line}`);
      }
      out.push(` ${lines[i] as string}`);
    }
    for (const insertion of hunk.insertions) {
      if (insertion.at === hunk.end) for (const line of insertion.lines) out.push(`+${line}`);
    }
    offset += added;
  }
  return out.join("\n") + "\n";
}
