/** A sub-app that conforms, and the tools to break it on purpose.
 *
 * ⭐ WHY THE BASELINE IS A WHOLE APP. Every violating fixture in these
 * tests is this app with ONE thing changed, which is what makes each test
 * a statement about one rule instead of a statement about a hand-written
 * snippet that happens to fail. It also means the conforming case is
 * tested constantly: if any rule starts firing on ordinary, correct code,
 * the baseline test goes red before anyone ships a gate that cries wolf.
 *
 * The files below are written the way the host's own hand-written sub-apps
 * are (`shell-reference`, `docusign`) — including the banners, which
 * matter: a real generated file's header explains that it must not cache a
 * boolean or interpolate into SQL, so it CONTAINS the strings the checks
 * look for. A gate that trips on its own explanation is a gate nobody can
 * use, so the baseline carries those sentences deliberately.
 *
 * ⛔ `editFile` THROWS WHEN THE EDIT DOES NOT APPLY. A violating fixture
 * that silently failed to violate anything would make its test pass for
 * the wrong reason, and that test would then guard nothing forever. */
import type { CandidateFile, CandidateSubApp } from "../analyze";

export const FIXTURE_ID = "wc-clock";

const MANIFEST = `/** Works council clock sub-app manifest — GENERATED by Flightdeck Studio.
 *
 * A sub-app is code-declared, not installed: this file does nothing until
 * \`server/subapps/registry.ts\` imports it and pushes it into
 * SUBAPP_MANIFESTS. That edit ships beside this file as a patch. */
import type { SubAppManifest } from "../types.js";
import { applyWcClockSchema } from "./schema.js";
import { registerWcClockRoutes } from "./routes/index.js";

export const wcClockManifest: SubAppManifest = {
  // LOCKED from this point forward: the kill-switch env var
  // SUBAPP_WC_CLOCK_ENABLED, the /console/apps/wc-clock nav path and the
  // subapp_wc_clock_ table prefix are all derived from this id.
  id: "wc-clock",
  // Literal English — nav and Catalog render this verbatim.
  label: "Works council clock",
  version: "0.1.0",
  minHostVersion: "5.0.0",
  icon: "🕐",
  navSection: "Contract pipeline",
  routePrefix: "/api/apps/wc-clock",
  webModuleId: "wc-clock",
  capabilities: ["read:contracts"],
  visibleToRoles: ["hr_reviewer", "wc_liaison"],
  initSchema: (db) => applyWcClockSchema(db),
  registerRoutes: (app, ctx) => registerWcClockRoutes(app, ctx),
};
`;

const GUARD = `/** requireWcClockEnabled — GENERATED. Re-reads the kill switch AND this
 * project's own live install row on EVERY call (never a cached boolean).
 *
 * The three-layer AND: \`SUBAPP_WC_CLOCK_ENABLED\` === "true", the '*'
 * ceiling row, and this project's row. Fail-closed, default OFF. A
 * module-level process.env capture would make the kill switch a
 * restart-only control, so the env var is read per call, inside the
 * function, through subAppKillSwitchEnabled.
 *
 * ⛔ Imports only LEAF modules (../installRow.js, ../killSwitch.js).
 * Reaching ../registry.js for the same data would pull every sibling
 * sub-app into this file's import closure. */
import type { FastifyRequest } from "fastify";
import { appendFlightdeckAudit } from "../../lib/flightdeckAudit.js";
import { effectiveSubAppEnabled } from "../installRow.js";
import { subAppKillSwitchEnabled } from "../killSwitch.js";
import { DEFAULT_PROJECT_ID } from "../../project/types.js";
import type { WorkspaceRuntime } from "../../workspace/types.js";

export const WC_CLOCK_SUBAPP_ID = "wc-clock";

export class WcClockDisabledError extends Error {}

export async function requireWcClockEnabled(req: FastifyRequest): Promise<WorkspaceRuntime> {
  const rt = req.workspace;
  const killSwitchOn = subAppKillSwitchEnabled(WC_CLOCK_SUBAPP_ID);
  const state = rt
    ? await effectiveSubAppEnabled(rt.db, req.project?.id ?? DEFAULT_PROJECT_ID, WC_CLOCK_SUBAPP_ID)
    : null;
  const enabled = killSwitchOn && state?.enabled === true;

  if (!enabled) {
    if (rt) {
      appendFlightdeckAudit(rt.root, {
        event: "wc-clock.access.refused",
        actor: req.principal?.username ?? "anonymous",
        reason: !killSwitchOn ? "kill-switch-off" : "not-installed-or-disabled",
      });
    }
    throw new WcClockDisabledError("Works council clock sub-app is not enabled for this workspace");
  }

  return rt as WorkspaceRuntime;
}
`;

const SCHEMA = `/** Works council clock schema — GENERATED. The COMPLETE
 * \`subapp_wc_clock_*\` DDL, written once. Idempotent CREATE TABLE IF NOT
 * EXISTS: initSchema runs on every boot, for every workspace. */
import type { Db } from "../../db.js";

export const WC_CLOCK_SCHEMA = \`
CREATE TABLE IF NOT EXISTS subapp_wc_clock_entries(
  id TEXT PRIMARY KEY,
  ticket TEXT NOT NULL,
  minutes INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  created_by TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_wc_clock_entries_ticket ON subapp_wc_clock_entries(ticket);
\`;

export async function applyWcClockSchema(db: Db): Promise<void> {
  await db.exec(WC_CLOCK_SCHEMA);
}
`;

const ROUTES_INDEX = `/** Works council clock route aggregator — GENERATED. One import and one
 * call per domain; manifest.ts names this file and nothing else. */
import type { FastifyInstance } from "fastify";
import type { RegisterRoutesCtx } from "../../types.js";
import { registerWcClockEntriesRoutes } from "./entries.js";

export function registerWcClockRoutes(app: FastifyInstance, ctx: RegisterRoutesCtx): void {
  registerWcClockEntriesRoutes(app, ctx);
}
`;

const ROUTES_ENTRIES = `/** Works council clock — entries routes. GENERATED.
 *
 * \`requireWcClockEnabled\` is the FIRST statement in every handler below,
 * and its refusal is mapped to a 403. The shell's manifest-derived RBAC
 * rule checks ROLES ONLY and never enable-state, so a handler missing that
 * call would answer with the kill switch off.
 *
 * ⛔ Contracts and the audit log are reached ONLY through
 * ctx.capabilitiesFor(...) — never a node:fs or database-driver import of
 * this file's own. */
import { z } from "zod";
import type { FastifyInstance, FastifyReply } from "fastify";
import type { RegisterRoutesCtx } from "../../types.js";
import type { WorkspaceRuntime } from "../../../workspace/types.js";
import { WC_CLOCK_SUBAPP_ID, WcClockDisabledError, requireWcClockEnabled } from "../guard.js";

/** Forced by codegen, never taken from the spec: a ticket becomes part of
 * a proposal FILENAME. */
const TICKET_RE = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

const logEntryBody = z
  .object({
    ticket: z.string().regex(TICKET_RE, "must be 1-64 characters of A-Z a-z 0-9 . _ -"),
    minutes: z.number().int(),
  })
  .strict();

/** One refusal map for the whole file. An error this does not recognise is
 * RETHROWN, not swallowed into a 500 that hides it. */
function mapError(reply: FastifyReply, err: unknown) {
  if (err instanceof WcClockDisabledError) {
    return reply.code(403).send({ error: err.message, code: "subapp_disabled" });
  }
  throw err;
}

export function registerWcClockEntriesRoutes(app: FastifyInstance, ctx: RegisterRoutesCtx): void {
  app.get("/api/apps/wc-clock/entries", async (req, reply) => {
    try {
      const rt: WorkspaceRuntime = await requireWcClockEnabled(req);
      const rows = await rt.db.all(
        "SELECT id, ticket, minutes, created_at FROM subapp_wc_clock_entries ORDER BY created_at DESC LIMIT 200",
      );
      return reply.send({ entries: rows });
    } catch (err) {
      return mapError(reply, err);
    }
  });

  app.post("/api/apps/wc-clock/entries", async (req, reply) => {
    try {
      const rt: WorkspaceRuntime = await requireWcClockEnabled(req);
      const parsed = logEntryBody.safeParse(req.body);
      if (!parsed.success) {
        return reply.code(400).send({ error: "invalid body", code: "invalid_body" });
      }
      const caps = ctx.capabilitiesFor(WC_CLOCK_SUBAPP_ID);
      await rt.db.run(
        "INSERT INTO subapp_wc_clock_entries(id, ticket, minutes, created_at, created_by) VALUES(?, ?, ?, ?, ?)",
        [crypto.randomUUID(), parsed.data.ticket, parsed.data.minutes, new Date().toISOString(), req.principal?.username ?? "anonymous"],
      );
      caps.auditAppend({ event: "wc-clock.entry.logged", fields: Object.keys(parsed.data) });
      return reply.code(201).send({ ok: true });
    } catch (err) {
      return mapError(reply, err);
    }
  });
}
`;

const WEB_MODULE = `/** Works council clock — GENERATED page. Default-exports a SubAppModule;
 * the web loader globs this exact path and lazy-mounts .Page.
 *
 * ⚠ English-only, deliberately: a dictionary would need a static import
 * and a spread in web/src/i18n.ts AND an update to the EXACT frozen key
 * counts in tests/subapps/i18nSplit.test.ts. */
import { useCallback, useEffect, useState } from "react";
import type { SubAppModule } from "../registry";

const ROUTE_PREFIX = "/api/apps/wc-clock";
const APP_TITLE = "Works council clock";

export function Page() {
  const [entries, setEntries] = useState([]);
  const [error, setError] = useState(null);

  const load = useCallback(async () => {
    const res = await fetch(ROUTE_PREFIX + "/entries");
    if (res.status === 403) {
      setError("This app is not enabled for your workspace.");
      return;
    }
    const body = await res.json();
    setEntries(body.entries);
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <div className="page">
      <h1>{APP_TITLE}</h1>
      {error ? <p className="errorbox">{error}</p> : <p className="muted">{entries.length} entries</p>}
    </div>
  );
}

const wcClockModule: SubAppModule = { Page };
export default wcClockModule;
`;

const REGISTRY_PATCH = `--- a/server/subapps/registry.ts
+++ b/server/subapps/registry.ts
@@ -4,6 +4,7 @@
 import { shellReferenceManifest } from "./shell-reference/manifest.js";
+import { wcClockManifest } from "./wc-clock/manifest.js";
 
 export const SUBAPP_MANIFESTS: SubAppManifest[] = [
   shellReferenceManifest,
+  // Generated by Flightdeck Studio. Kill switch: SUBAPP_WC_CLOCK_ENABLED
+  wcClockManifest,
 ];
`;

export const MANIFEST_PATH = "server/subapps/wc-clock/manifest.ts";
export const GUARD_PATH = "server/subapps/wc-clock/guard.ts";
export const SCHEMA_PATH = "server/subapps/wc-clock/schema.ts";
export const ROUTES_INDEX_PATH = "server/subapps/wc-clock/routes/index.ts";
export const ROUTES_PATH = "server/subapps/wc-clock/routes/entries.ts";
export const WEB_PATH = "web/src/subapps/wc-clock/index.tsx";
export const PATCH_PATH = "server/subapps/registry.ts.patch";

/** The baseline: a sub-app that mounts, guards, namespaces its tables and
 * reaches nothing it was not granted. */
export function conformingSubApp(): CandidateSubApp {
  return {
    files: [
      { path: MANIFEST_PATH, contents: MANIFEST },
      { path: GUARD_PATH, contents: GUARD },
      { path: SCHEMA_PATH, contents: SCHEMA },
      { path: ROUTES_INDEX_PATH, contents: ROUTES_INDEX },
      { path: ROUTES_PATH, contents: ROUTES_ENTRIES },
      { path: WEB_PATH, contents: WEB_MODULE },
      { path: PATCH_PATH, contents: REGISTRY_PATCH },
    ],
  };
}

export function fileIn(app: CandidateSubApp, path: string): CandidateFile {
  const file = app.files.find((candidate) => candidate.path === path);
  if (file === undefined) throw new Error(`fixture has no file at ${path}`);
  return file;
}

/** Replace `find` with `replacement` in one file. Throws when `find` is
 * not there — a fixture that failed to break is a test that proves
 * nothing, and it must fail loudly rather than pass quietly. */
export function editFile(app: CandidateSubApp, path: string, find: string, replacement: string): CandidateSubApp {
  const target = fileIn(app, path);
  if (!target.contents.includes(find)) {
    throw new Error(`fixture edit did not apply: ${path} does not contain ${JSON.stringify(find)}`);
  }
  return {
    files: app.files.map((file) => (file.path === path ? { path, contents: file.contents.replace(find, replacement) } : file)),
  };
}

/** Add a file, or replace one wholesale. */
export function withFile(app: CandidateSubApp, path: string, contents: string): CandidateSubApp {
  const exists = app.files.some((file) => file.path === path);
  return {
    files: exists
      ? app.files.map((file) => (file.path === path ? { path, contents } : file))
      : [...app.files, { path, contents }],
  };
}

export function withoutFile(app: CandidateSubApp, path: string): CandidateSubApp {
  const before = app.files.length;
  const files = app.files.filter((file) => file.path !== path);
  if (files.length === before) throw new Error(`fixture has no file at ${path} to remove`);
  return { files };
}
