/** Studio refuses before it does anything — GENERATED BY STUDIO, and meant to
 * stay.
 *
 * ⭐ WHY THIS IS THE MOST LOAD-BEARING TEST STUDIO SHIPS. The shell's
 * manifest-derived RBAC rule enforces ROLES ONLY. Nothing in the host checks
 * enable-state for a sub-app's own routes, so a Studio handler that parsed a
 * body before calling `requireStudioEnabled`, or that called it in two
 * handlers out of three, would do real work with the kill switch off — and the
 * kill switch is the operational control somebody reaches for when a sub-app
 * is misbehaving in production.
 *
 * ⭐ TESTED TWO WAYS, ON PURPOSE. The first half runs the real routes on a
 * real Fastify and reads the ANSWER: a request the workspace resolver could
 * not place must come back 403 `subapp_disabled`, with the capability adapter
 * never asked for, even when the body is garbage that could not survive a
 * schema. If the guard ran second, one or the other would differ. The second
 * half reads the SOURCE, because "first" is a positional property that a
 * passing request cannot distinguish from "first among the statements that
 * happened to matter for this input".
 *
 * ⛔ IT DELIBERATELY DOES NOT EXERCISE THE ENABLED PATH. Doing that needs a
 * live install row and a workspace database — host machinery Studio is
 * generated outside of and has never seen. A test that guessed at those shapes
 * would be a test about the guess. The refusal path needs none of it, and the
 * refusal path is the one with consequences. */
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import fastify, { type FastifyInstance } from "fastify";
import { STUDIO_SUBAPP_ID, StudioDisabledError, requireStudioEnabled } from "../../../server/subapps/studio/guard.js";
import { registerStudioRoutes } from "../../../server/subapps/studio/routes/index.js";
import type { RegisterRoutesCtx, SubAppCapabilities } from "../../../server/subapps/types.js";

const SUBAPP_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "../../../server/subapps/studio");

function read(relative: string): string {
  return readFileSync(join(SUBAPP_DIR, relative), "utf8");
}

/** Every file of Studio's that is MOUNTED — the guard, the routes and the
 * service modules a route reaches. Not the web module: a page is not a
 * handler. */
const MOUNTED_SERVER_FILES = [
  "guard.ts",
  "manifest.ts",
  "routes/index.ts",
  "service/admit.ts",
  "service/bundle.ts",
  "service/proposal.ts",
];

/* ══════════════════════════════════════════════════════════════════════════
 * The answer a disabled Studio gives
 * ═══════════════════════════════════════════════════════════════════════ */

/** A capability adapter that records being ASKED FOR. Nothing calls through
 * it in this file — the claim under test is that nothing ever gets that far. */
function buildApp(): { app: FastifyInstance; adapterRequests: string[] } {
  const adapterRequests: string[] = [];
  const ctx: RegisterRoutesCtx = {
    capabilitiesFor: async (workspaceId: string) => {
      adapterRequests.push(workspaceId);
      throw new Error("the adapter must never be resolved for a refused request");
      // eslint-disable-next-line no-unreachable
      return undefined as unknown as SubAppCapabilities;
    },
  };
  const app = fastify();
  app.decorateRequest("workspace", null);
  app.decorateRequest("project", null);
  app.decorateRequest("principal", null);
  // No workspace: the request the resolver could not place. Fail-closed,
  // default OFF, and no host database needed to prove it.
  app.addHook("onRequest", async (req) => {
    req.workspace = null;
    req.project = null;
    req.principal = null;
  });
  registerStudioRoutes(app, ctx);
  return { app, adapterRequests };
}

const ROUTES = [
  { method: "GET" as const, url: "/api/apps/studio/proposals", payload: undefined },
  { method: "POST" as const, url: "/api/apps/studio/admit", payload: { bundle: "studio-mini-app/1" } },
  { method: "POST" as const, url: "/api/apps/studio/proposals", payload: { bundle: "studio-mini-app/1" } },
];

describe("every Studio handler refuses before it does anything", () => {
  for (const route of ROUTES) {
    it(`${route.method} ${route.url} answers 403 subapp_disabled and never resolves an adapter`, async () => {
      const { app, adapterRequests } = buildApp();
      await app.ready();
      try {
        const res = await app.inject({
          method: route.method,
          url: route.url,
          ...(route.payload === undefined ? {} : { payload: route.payload }),
        });
        expect(res.statusCode).toBe(403);
        expect(res.json()).toMatchObject({ code: "subapp_disabled" });
        expect(adapterRequests).toEqual([]);
      } finally {
        await app.close();
      }
    });
  }

  it("a body that could not possibly parse still answers 403, never 400", async () => {
    // If the guard ran after the schema, this would be a 400. That is the
    // whole difference between "checks enable-state" and "checks enable-state
    // first".
    const { app } = buildApp();
    await app.ready();
    try {
      const res = await app.inject({
        method: "POST",
        url: "/api/apps/studio/proposals",
        payload: { nonsense: [1, 2, 3], bundle: 17 },
      });
      expect(res.statusCode).toBe(403);
      expect(res.json()).toMatchObject({ code: "subapp_disabled" });
    } finally {
      await app.close();
    }
  });

  it("the guard itself refuses a request with no workspace, and refuses by throwing", async () => {
    const req = { workspace: null, project: null, principal: null } as unknown as Parameters<typeof requireStudioEnabled>[0];
    await expect(requireStudioEnabled(req)).rejects.toBeInstanceOf(StudioDisabledError);
  });
});

/* ══════════════════════════════════════════════════════════════════════════
 * "First" as a positional property of the source
 * ═══════════════════════════════════════════════════════════════════════ */

describe("the guard call comes before any work, in every handler", () => {
  it("registers handlers at all — a loop over an empty list is a green test that proves nothing", () => {
    const handlers = read("routes/index.ts").split(/\bapp\.(?:get|post|put|patch|delete)\s*\(/).slice(1);
    expect(handlers.length).toBeGreaterThanOrEqual(3);
  });

  it("calls requireStudioEnabled before parsing, before the adapter, before anything", () => {
    const source = read("routes/index.ts");
    const handlers = source.split(/\bapp\.(?:get|post|put|patch|delete)\s*\(/).slice(1);
    for (const handler of handlers) {
      const guardAt = handler.indexOf("requireStudioEnabled");
      expect(guardAt, "a handler never calls the guard").toBeGreaterThan(-1);
      for (const token of ["safeParse", "req.body", "req.params", "req.query", "capabilitiesFor", "rt.db"]) {
        const at = handler.indexOf(token);
        expect(at === -1 || at > guardAt, `a handler reaches ${token} before the guard`).toBe(true);
      }
    }
  });

  it("imports the guard rather than assuming it", () => {
    expect(read("routes/index.ts")).toMatch(/import\s*\{[^}]*requireStudioEnabled[^}]*\}\s*from\s*"\.\.\/guard\.js"/);
  });
});

describe("nothing mounted caches a boolean or reaches a disk", () => {
  it("reads no env var of its own outside the guard's own host leaves", () => {
    for (const file of MOUNTED_SERVER_FILES) {
      expect(read(file).includes("process.env"), `${file} reads process.env`).toBe(false);
    }
  });

  it("imports no node builtin and no database driver", () => {
    for (const file of MOUNTED_SERVER_FILES) {
      const source = read(file);
      expect(source, `${file} imports a node builtin`).not.toMatch(/from\s+"node:/);
      expect(source, `${file} imports a database driver`).not.toMatch(/from\s+"(better-sqlite3|pg|mysql2?|knex|drizzle-orm|typeorm)"/);
    }
  });

  it("never reaches the host registry or a sibling sub-app", () => {
    for (const file of MOUNTED_SERVER_FILES) {
      const source = read(file);
      expect(source, `${file} imports the registry`).not.toMatch(/from\s+"[^"]*\/registry\.js"/);
      expect(source, `${file} imports installRoutes`).not.toMatch(/from\s+"[^"]*installRoutes\.js"/);
    }
  });

  it("names no engine package — the whole reason this sub-app is installable", () => {
    // The earlier version of this sub-app imported `@spec`, `@codegen/pure`
    // and `@conformance/gate` from Studio's repo. Those imports mounted fine
    // and were still uninstallable: they are forty-six modules of somebody
    // else's source, authored against somebody else's tsconfig, and the host's
    // own `npm run typecheck` went red on the copy.
    for (const file of MOUNTED_SERVER_FILES) {
      const source = read(file);
      expect(source, `${file} imports a Studio engine package`).not.toMatch(/from\s+"@(spec|codegen|conformance)/);
    }
  });

  it("names only the two packages the host already carries", () => {
    for (const file of MOUNTED_SERVER_FILES) {
      for (const match of read(file).matchAll(/\bfrom\s+"([^".][^"]*)"/g)) {
        const specifier = match[1] ?? "";
        if (specifier.startsWith(".")) continue;
        expect(["zod", "fastify"], `${file} imports ${specifier}`).toContain(specifier);
      }
    }
  });
});

describe("the sub-app's own shape", () => {
  it("is database-free: no schema.ts, and initSchema does nothing", () => {
    expect(read("manifest.ts")).toContain("initSchema: () => {}");
    expect(() => read("schema.ts")).toThrow();
  });

  it("audits its refusal, and distinguishes the kill switch from the install row", () => {
    const guard = read("guard.ts");
    expect(guard).toContain("appendFlightdeckAudit");
    expect(guard).toContain("kill-switch-off");
    expect(guard).toContain("not-installed-or-disabled");
  });

  it("names itself consistently, so the kill switch an operator flips is the one it reads", () => {
    expect(STUDIO_SUBAPP_ID).toBe("studio");
    expect(read("manifest.ts")).toContain('routePrefix: "/api/apps/studio"');
  });
});
