/** Studio's admission checks, exercised — GENERATED BY STUDIO, and meant to
 * stay.
 *
 * ⭐ WHY THIS FILE SHIPS INTO THE HOST. Studio's sub-app has one job with
 * consequences: deciding which bundles are allowed to become a proposal that a
 * person will paste into this repository. Every rule that decision rests on
 * lives in `server/subapps/studio/service/admit.ts`, in this repo, and is
 * therefore editable by anyone working in this repo. A rule with no test is a
 * rule the next hand-edit silently removes, and the failure mode is a proposal
 * naming a path nobody checked.
 *
 * ⭐ AND WHY IT IMPORTS NOTHING OF THE HOST'S. Every import below is either a
 * Studio file, `vitest`, or a node builtin. That is deliberate: Studio is
 * generated outside this checkout, so a test it emits cannot be written
 * against host internals it has never seen without guessing at their shapes.
 * What it CAN do is hold Studio's own code to Studio's own contract, here,
 * under this repo's vitest run — and pin the host's five closed literal lists
 * beside the manifest Studio declares, so a drift in either shows up red.
 *
 * Placed in `tests/subapps/studio/` because the host's G3 layout fence
 * (`tests/subapps/subappManifest.test.ts`) requires a sub-app's tests to live
 * in their own folder rather than the flat `tests/` root. The vitest glob is
 * already recursive, so placing it is all the wiring there is. */
import { describe, expect, it } from "vitest";
import {
  ADMISSION_CHECKS,
  HOST_CAPABILITIES,
  HOST_NAV_SECTIONS,
  HOST_ROLES,
  HOST_VERSION,
  admitBundle,
  demandsNewerHost,
} from "../../../server/subapps/studio/service/admit.js";
import { STUDIO_BUNDLE_SCHEMA, studioBundleSchema, type StudioBundle } from "../../../server/subapps/studio/service/bundle.js";
import { studioManifest } from "../../../server/subapps/studio/manifest.js";

/* ══════════════════════════════════════════════════════════════════════════
 * A bundle that should pass, written out in full
 *
 * Deliberately a literal rather than a call into Studio's generator: the
 * generator does not exist in this repository, and a fixture that could only
 * be produced by the thing under test would make a red run ambiguous between
 * "admission broke" and "generation changed". This is what arrives on the
 * wire, spelled the way it arrives.
 * ═══════════════════════════════════════════════════════════════════════ */

const MANIFEST_TS = `import type { SubAppManifest } from "../types.js";
import { registerWcClockRoutes } from "./routes/index.js";

export const wcClockManifest: SubAppManifest = {
  id: "wc-clock",
  label: "Works council clock",
  version: "0.1.0",
  minHostVersion: "5.0.0",
  icon: "\\u23f1\\ufe0f",
  navSection: "Contract pipeline",
  routePrefix: "/api/apps/wc-clock",
  webModuleId: "wc-clock",
  capabilities: ["read:contracts"],
  visibleToRoles: ["wc_liaison", "admin"],
  initSchema: () => {},
  registerRoutes: (app, ctx) => registerWcClockRoutes(app, ctx),
};
`;

const GUARD_TS = `import type { FastifyRequest } from "fastify";
import { appendFlightdeckAudit } from "../../lib/flightdeckAudit.js";
import { effectiveSubAppEnabled } from "../installRow.js";
import { subAppKillSwitchEnabled } from "../killSwitch.js";
import { DEFAULT_PROJECT_ID } from "../../project/types.js";
import type { WorkspaceRuntime } from "../../../workspace/types.js";

export class WcClockDisabledError extends Error {}

export async function requireWcClockEnabled(req: FastifyRequest): Promise<WorkspaceRuntime> {
  const rt = req.workspace;
  const on = subAppKillSwitchEnabled("wc-clock");
  const state = rt ? await effectiveSubAppEnabled(rt.db, req.project?.id ?? DEFAULT_PROJECT_ID, "wc-clock") : null;
  if (!(on && state?.enabled === true)) {
    if (rt) appendFlightdeckAudit(rt.root, { event: "wc-clock.access.refused", reason: on ? "not-installed" : "kill-switch-off" });
    throw new WcClockDisabledError("wc-clock is not enabled for this workspace");
  }
  return rt as WorkspaceRuntime;
}
`;

const ROUTES_TS = `import { z } from "zod";
import type { FastifyInstance } from "fastify";
import type { RegisterRoutesCtx } from "../../types.js";
import type { WorkspaceRuntime } from "../../../workspace/types.js";
import { requireWcClockEnabled } from "../guard.js";

const body = z.object({ ticket: z.string().max(64) }).strict();

export function registerWcClockRoutes(app: FastifyInstance, ctx: RegisterRoutesCtx): void {
  app.get("/api/apps/wc-clock/contracts", async (req, reply) => {
    let rt: WorkspaceRuntime;
    try {
      rt = await requireWcClockEnabled(req);
    } catch {
      return reply.code(403).send({ error: "disabled", code: "subapp_disabled" });
    }
    const caps = await ctx.capabilitiesFor(rt.id);
    return { contracts: caps.readContracts() };
  });

  app.post("/api/apps/wc-clock/proposals", async (req, reply) => {
    let rt: WorkspaceRuntime;
    try {
      rt = await requireWcClockEnabled(req);
    } catch {
      return reply.code(403).send({ error: "disabled", code: "subapp_disabled" });
    }
    const parsed = body.safeParse(req.body);
    if (!parsed.success) return reply.code(400).send({ error: "invalid body" });
    const caps = await ctx.capabilitiesFor(rt.id);
    return { path: caps.writeInboxProposal("wc-clock-1.json", parsed.data) };
  });
}
`;

const WEB_TSX = `import type { SubAppModule } from "../registry";

function Page() {
  return <div className="page">Works council clock</div>;
}

const wcClockModule: SubAppModule = { Page };
export default wcClockModule;
`;

const HOST_TEST_TS = `import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

describe("wc-clock", () => {
  it("has a manifest on disk", () => {
    expect(fs.existsSync(path.join(process.cwd(), "server", "subapps", "wc-clock", "manifest.ts"))).toBe(true);
  });
});
`;

function validBundle(): StudioBundle {
  return {
    bundle: STUDIO_BUNDLE_SCHEMA,
    producedBy: "flightdeck-studio/0.1.0",
    producedAt: "2026-09-20T09:00:00.000Z",
    subAppId: "wc-clock",
    label: "Works council clock",
    spec: {
      id: "wc-clock",
      label: "Works council clock",
      icon: "⏱️",
      version: "0.1.0",
      minHostVersion: "5.0.0",
      navSection: "Contract pipeline",
      routePrefix: "/api/apps/wc-clock",
      webModuleId: "wc-clock",
      enableEnvVar: "SUBAPP_WC_CLOCK_ENABLED",
      purpose: "Track the German works-council consultation clock for one contract folder.",
      capabilities: ["read:contracts"],
      visibleToRoles: ["wc_liaison", "admin"],
      steps: [
        { ordinal: "1", title: "Read state", kind: "read", gated: false },
        { ordinal: "2", title: "Notify the liaison", kind: "propose", gated: true },
      ],
    },
    files: [
      { path: "server/subapps/wc-clock/manifest.ts", kind: "manifest", contents: MANIFEST_TS },
      { path: "server/subapps/wc-clock/guard.ts", kind: "guard", contents: GUARD_TS },
      { path: "server/subapps/wc-clock/routes/index.ts", kind: "routes-index", contents: ROUTES_TS },
      { path: "web/src/subapps/wc-clock/index.tsx", kind: "web-module", contents: WEB_TSX },
      { path: "tests/subapps/wc-clock/wcClockConformance.test.ts", kind: "host-test", contents: HOST_TEST_TS },
    ],
    registry: {
      file: "server/subapps/registry.ts",
      importLine: 'import { wcClockManifest } from "./wc-clock/manifest.js";',
      entryLines: ["  // Works council clock. Kill switch: SUBAPP_WC_CLOCK_ENABLED", "  wcClockManifest,"],
    },
    gate: {
      ok: true,
      checks: ["manifest", "import-closure", "capability-escape", "guard-first", "cached-boolean", "table-prefix", "mount"],
      findings: [],
      filesChecked: 5,
    },
    warnings: [],
    workflowSource: "skills/wc-clock/SKILL.md",
  };
}

/** Rule ids of the ERROR findings, which is what every refusal test asserts
 * on. Message text is prose and may be improved; the rule id is the contract. */
function errorRules(bundle: StudioBundle): string[] {
  return [...new Set(admitBundle(bundle).errors.map((finding) => finding.rule))].sort();
}

/* ══════════════════════════════════════════════════════════════════════════
 * The tests
 * ═══════════════════════════════════════════════════════════════════════ */

describe("the wire schema", () => {
  it("accepts a well-formed bundle, so every refusal below is about admission and not about parsing", () => {
    const parsed = studioBundleSchema.safeParse(validBundle());
    expect(parsed.success, JSON.stringify(parsed.success ? [] : parsed.error.issues)).toBe(true);
  });

  it("refuses an unknown key rather than ignoring it — .strict() is not decoration", () => {
    const parsed = studioBundleSchema.safeParse({ ...validBundle(), install: true });
    expect(parsed.success).toBe(false);
  });

  it("refuses a bundle that does not say what wire format it is", () => {
    const { bundle: _schema, ...rest } = validBundle();
    expect(studioBundleSchema.safeParse(rest).success).toBe(false);
    expect(studioBundleSchema.safeParse({ ...validBundle(), bundle: "studio-mini-app/2" }).success).toBe(false);
  });
});

describe("a clean bundle is admitted", () => {
  it("passes, and reports every check that RAN by name", () => {
    const report = admitBundle(validBundle());
    expect(report.errors, JSON.stringify(report.errors)).toEqual([]);
    expect(report.ok).toBe(true);
    // "Nothing was wrong" must never look like "nothing ran".
    expect(report.checks).toEqual(["bundle-size", ...ADMISSION_CHECKS.map((check) => check.name)]);
    expect(report.checks.length).toBeGreaterThan(5);
    expect(report.filesChecked).toBe(5);
  });

  it("still reports its advisory findings — a warning is not a silence", () => {
    // The mini-app floor: no schema.ts. Said out loud so a reviewer can see
    // the absence was noticed rather than missed.
    const report = admitBundle(validBundle());
    expect(report.warnings.map((finding) => finding.rule)).toContain("ADM-020");
    expect(report.ok).toBe(true);
  });
});

describe("ADM-020 — where the files would land", () => {
  it("refuses a path that climbs out of the repository", () => {
    const bundle = validBundle();
    bundle.files[0] = { ...(bundle.files[0] as StudioBundle["files"][number]), path: "../../../.ssh/authorized_keys" };
    expect(errorRules(bundle)).toContain("ADM-020");
    expect(admitBundle(bundle).ok).toBe(false);
  });

  it("refuses a path that edits a host file rather than adding a sub-app one", () => {
    const bundle = validBundle();
    bundle.files.push({ path: "server/subapps/registry.ts", kind: "registry", contents: "export const SUBAPP_MANIFESTS = [];\n" });
    expect(errorRules(bundle)).toContain("ADM-020");
  });

  it("refuses a path belonging to a DIFFERENT sub-app", () => {
    const bundle = validBundle();
    bundle.files.push({ path: "server/subapps/docusign/routes/index.ts", kind: "routes-index", contents: "export {};\n" });
    expect(errorRules(bundle)).toContain("ADM-020");
  });

  it("refuses a bundle with no manifest and one with no web module", () => {
    const withoutManifest = validBundle();
    withoutManifest.files = withoutManifest.files.filter((file) => !file.path.endsWith("/manifest.ts"));
    expect(errorRules(withoutManifest)).toContain("ADM-020");

    const withoutWeb = validBundle();
    withoutWeb.files = withoutWeb.files.filter((file) => !file.path.startsWith("web/"));
    expect(errorRules(withoutWeb)).toContain("ADM-020");
  });

  it("refuses the same path twice, because one of the two contents would be lost", () => {
    const bundle = validBundle();
    bundle.files.push({ ...(bundle.files[0] as StudioBundle["files"][number]), contents: "export {};\n" });
    expect(errorRules(bundle)).toContain("ADM-020");
  });

  it("refuses a stylesheet: every sub-app's CSS lives in the host's shared theme.css", () => {
    const bundle = validBundle();
    bundle.files.push({ path: "web/src/subapps/wc-clock/styles.css", kind: "style", contents: ".page { color: red; }\n" });
    expect(errorRules(bundle)).toContain("ADM-020");
  });
});

describe("ADM-040 — what the proposed code could reach", () => {
  it("refuses a node builtin in a mounted server module, even unused", () => {
    const bundle = validBundle();
    const routes = bundle.files[2] as StudioBundle["files"][number];
    bundle.files[2] = { ...routes, contents: `import fs from "node:fs";\n${routes.contents}` };
    expect(errorRules(bundle)).toContain("ADM-040");
  });

  it("refuses a database driver", () => {
    const bundle = validBundle();
    const routes = bundle.files[2] as StudioBundle["files"][number];
    bundle.files[2] = { ...routes, contents: `import Database from "better-sqlite3";\n${routes.contents}` };
    expect(errorRules(bundle)).toContain("ADM-040");
  });

  it("refuses reaching the host registry, which would drag every sibling sub-app into the closure", () => {
    const bundle = validBundle();
    const routes = bundle.files[2] as StudioBundle["files"][number];
    bundle.files[2] = { ...routes, contents: `import { SUBAPP_MANIFESTS } from "../../registry.js";\n${routes.contents}` };
    expect(errorRules(bundle)).toContain("ADM-040");
  });

  it("refuses a module-level process.env read — the kill switch is re-read per request", () => {
    const bundle = validBundle();
    const routes = bundle.files[2] as StudioBundle["files"][number];
    bundle.files[2] = { ...routes, contents: `const ON = process.env.SUBAPP_WC_CLOCK_ENABLED === "true";\n${routes.contents}` };
    expect(errorRules(bundle)).toContain("ADM-040");
  });

  it("allows exactly the two packages the host already carries, and nothing else", () => {
    const bundle = validBundle();
    const routes = bundle.files[2] as StudioBundle["files"][number];
    bundle.files[2] = { ...routes, contents: `import axios from "axios";\n${routes.contents}` };
    expect(errorRules(bundle)).toContain("ADM-040");
  });
});

describe("ADM-050 — the guard is the first statement, not the first interesting one", () => {
  it("refuses a handler that parses the body before it checks enable-state", () => {
    const bundle = validBundle();
    const routes = bundle.files[2] as StudioBundle["files"][number];
    bundle.files[2] = {
      ...routes,
      contents: routes.contents.replace(
        `    let rt: WorkspaceRuntime;
    try {
      rt = await requireWcClockEnabled(req);
    } catch {
      return reply.code(403).send({ error: "disabled", code: "subapp_disabled" });
    }
    const parsed = body.safeParse(req.body);`,
        `    const parsed = body.safeParse(req.body);
    let rt: WorkspaceRuntime;
    try {
      rt = await requireWcClockEnabled(req);
    } catch {
      return reply.code(403).send({ error: "disabled", code: "subapp_disabled" });
    }`,
      ),
    };
    expect(errorRules(bundle)).toContain("ADM-050");
  });

  it("refuses a handler that never calls the guard at all", () => {
    const bundle = validBundle();
    const routes = bundle.files[2] as StudioBundle["files"][number];
    bundle.files[2] = {
      ...routes,
      contents: `${routes.contents}\nexport function extra(app: FastifyInstance): void {\n  app.get("/api/apps/wc-clock/open", async () => ({ ok: true }));\n}\n`,
    };
    expect(errorRules(bundle)).toContain("ADM-050");
  });

  it("refuses a guard that is spelled but not imported", () => {
    const bundle = validBundle();
    const routes = bundle.files[2] as StudioBundle["files"][number];
    bundle.files[2] = {
      ...routes,
      contents: routes.contents.replace('import { requireWcClockEnabled } from "../guard.js";\n', ""),
    };
    expect(errorRules(bundle)).toContain("ADM-050");
  });
});

describe("ADM-010 and ADM-030 — would this manifest boot?", () => {
  it("refuses a routePrefix that is not the derivation of the id", () => {
    const bundle = validBundle();
    bundle.spec = { ...bundle.spec, routePrefix: "/api/apps/something-else" };
    expect(errorRules(bundle)).toContain("ADM-010");
  });

  it("refuses a bundle proposing the id `studio`, which would replace the thing filing it", () => {
    const bundle = validBundle();
    bundle.subAppId = "studio";
    bundle.spec = {
      ...bundle.spec,
      id: "studio",
      routePrefix: "/api/apps/studio",
      webModuleId: "studio",
      enableEnvVar: "SUBAPP_STUDIO_ENABLED",
    };
    expect(errorRules(bundle)).toContain("ADM-010");
  });

  it("refuses a navSection that is a near miss — the match is exact string equality", () => {
    const bundle = validBundle();
    bundle.spec = { ...bundle.spec, navSection: "Contract Pipeline" };
    expect(errorRules(bundle)).toContain("ADM-030");
  });

  it("refuses an empty visibleToRoles and an unknown role", () => {
    const empty = validBundle();
    empty.spec = { ...empty.spec, visibleToRoles: [] };
    expect(errorRules(empty)).toContain("ADM-030");

    const unknown = validBundle();
    unknown.spec = { ...unknown.spec, visibleToRoles: ["super_admin"] };
    expect(errorRules(unknown)).toContain("ADM-030");
  });

  it("refuses a capability the host cannot grant — the array IS the consent screen", () => {
    const bundle = validBundle();
    bundle.spec = { ...bundle.spec, capabilities: ["write:contracts"] };
    expect(errorRules(bundle)).toContain("ADM-030");
  });

  it("refuses a manifest demanding a host newer than this one", () => {
    const bundle = validBundle();
    bundle.spec = { ...bundle.spec, minHostVersion: "6.0.0" };
    expect(errorRules(bundle)).toContain("ADM-030");
    expect(demandsNewerHost("5.0.1", HOST_VERSION)).toBe(true);
    expect(demandsNewerHost("4.9.9", HOST_VERSION)).toBe(false);
    expect(demandsNewerHost(HOST_VERSION, HOST_VERSION)).toBe(false);
    // A version this host cannot compare is refused, never read as zero.
    expect(demandsNewerHost("latest", HOST_VERSION)).toBe(true);
  });
});

describe("ADM-060 — the registry lines are data a human pastes, never code", () => {
  it("refuses an entry line that is a statement rather than a manifest name", () => {
    const bundle = validBundle();
    bundle.registry = {
      ...bundle.registry,
      entryLines: ["  wcClockManifest,", '  ...(await import("node:child_process")).execSync("id"),'],
    };
    expect(errorRules(bundle)).toContain("ADM-060");
  });

  it("refuses an import line pointing anywhere but this sub-app's own manifest", () => {
    const bundle = validBundle();
    bundle.registry = { ...bundle.registry, importLine: 'import { x } from "../../../../evil.js";' };
    expect(errorRules(bundle)).toContain("ADM-060");
  });

  it("refuses a registry edit aimed at some other host file", () => {
    const bundle = validBundle();
    bundle.registry = { ...bundle.registry, file: "server/index.ts" };
    expect(errorRules(bundle)).toContain("ADM-060");
  });
});

describe("ADM-070 — the bundle's own report is a claim, and claims can be refused", () => {
  it("refuses a bundle that reports its own gate as blocked", () => {
    const bundle = validBundle();
    bundle.gate = { ...bundle.gate, ok: false };
    expect(errorRules(bundle)).toContain("ADM-070");
  });

  it("refuses a passing gate that names no checks — nothing ran is not a pass", () => {
    const bundle = validBundle();
    bundle.gate = { ...bundle.gate, checks: [] };
    expect(errorRules(bundle)).toContain("ADM-070");
  });

  it("refuses a report that contradicts itself", () => {
    const bundle = validBundle();
    bundle.gate = {
      ...bundle.gate,
      findings: [{ rule: "FD-C001", severity: "error", file: "server/subapps/wc-clock/routes/index.ts", line: 1, column: 1, message: "node builtin", evidence: null }],
    };
    expect(errorRules(bundle)).toContain("ADM-070");
  });

  it("does NOT admit a bundle on the strength of its own clean report", () => {
    // The whole point of the split: a perfect self-report next to a path that
    // escapes the sub-app's directories is still a refusal.
    const bundle = validBundle();
    bundle.files.push({ path: "scripts/gate.sh", kind: "script", contents: "#!/bin/sh\n" });
    const report = admitBundle(bundle);
    expect(bundle.gate.ok).toBe(true);
    expect(report.ok).toBe(false);
  });
});

describe("the host literals this sub-app judges against", () => {
  it("are the five, five and two the contract names", () => {
    expect([...HOST_NAV_SECTIONS]).toEqual(["Overview", "Contract pipeline", "Ops & insight", "Admin", "System apps"]);
    expect([...HOST_ROLES]).toEqual(["hr_preparer", "hr_reviewer", "wc_liaison", "legal", "admin"]);
    expect([...HOST_CAPABILITIES]).toEqual(["read:contracts", "write:inbox-proposal"]);
  });

  it("agree with the manifest Studio itself declares, which the host validates at boot", () => {
    // If these two ever disagree, one of them is wrong about the host — and
    // this is the cheapest place to find out.
    expect(HOST_NAV_SECTIONS as readonly string[]).toContain(studioManifest.navSection);
    expect(studioManifest.minHostVersion).toBe(HOST_VERSION);
    for (const role of studioManifest.visibleToRoles) expect(HOST_ROLES as readonly string[]).toContain(role);
    for (const scope of studioManifest.capabilities) expect(HOST_CAPABILITIES as readonly string[]).toContain(scope);
  });
});
