/** Studio's console page, rendered — GENERATED BY STUDIO, and meant to stay.
 *
 * ⭐ A DIFFERENT QUESTION FROM EVERY OTHER TEST STUDIO SHIPS.
 * `studioAdmission.test.ts` and `studioGuard.test.ts` ask about the server.
 * Neither can notice a component that throws on first render, a hook called
 * conditionally, or a `.map` over something that is not an array — and the
 * host mounts this module lazily through `import.meta.glob`, so a page that
 * throws fails at the moment a person clicks the nav item and nowhere earlier.
 *
 * It is a STATIC render, so `useEffect` never runs and no request is made.
 * What it proves is the FIRST PAINT: exactly the state a person sees before
 * the network answers, and the one a broken page fails in.
 *
 * ⭐ AND IT CHECKS THE TWO CLAIMS THE PAGE MUST NOT LET ANYONE MISBELIEVE.
 * First: that the button installs an app. It does not — the furthest this page
 * reaches is one file under `memory/proposals/`. Second: that the bundle's own
 * contract-gate report is this host's verdict. It is not, and the page has to
 * say which panel has authority. Both sentences have to be on screen before
 * anything is pasted, not in a toast afterwards, so both are asserted against
 * the rendered markup. The one claim that cannot be rendered — the file
 * control only exists once a bundle has been checked — is read off the source
 * instead, and says so on itself rather than being dressed up as a render
 * check. */
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import studioModule from "../../../web/src/subapps/studio/index.js";

const PAGE_SOURCE = readFileSync(
  resolve(dirname(fileURLToPath(import.meta.url)), "../../../web/src/subapps/studio/index.tsx"),
  "utf8",
);

const html = renderToStaticMarkup(createElement(studioModule.Page));

describe("the Studio page, rendered", () => {
  it("default-exports a SubAppModule with a Page the web loader can lazy-mount", () => {
    expect(typeof studioModule.Page).toBe("function");
  });

  it("paints on first render, before any request has answered", () => {
    expect(html.length).toBeGreaterThan(500);
    expect(html).toContain("File a generated mini-app for review");
  });

  it("says that filing a proposal installs nothing, before anything is pasted", () => {
    expect(html).toContain("Studio proposes. It does not install.");
    expect(html).toContain("memory/proposals/");
    expect(html).toMatch(/until a human adds those files/);
    expect(html).toMatch(/no path here that could install an app/);
  });

  it("repeats it on the control itself, for the person who scrolled past the notice", () => {
    // The file-the-proposal control only exists once a bundle has been
    // checked, so this claim is read off the SOURCE rather than the first
    // paint — and it is marked as such rather than dressed up as a render
    // assertion.
    expect(PAGE_SOURCE).toContain("File the proposal (installs nothing)");
    expect(PAGE_SOURCE).toContain("A human applies it.");
  });

  it("explains why the conversion is pasted rather than run here", () => {
    expect(html).toMatch(/runs in Studio, not here/);
    expect(html).toMatch(/could not build/);
  });

  it("keeps the host's own verdict and the bundle's self-report apart, by name", () => {
    // Rendered only once a bundle has been checked, so read off the source —
    // but the two headings and the sentence that says which one decides are
    // the whole reason the split is visible to a reviewer at all.
    expect(PAGE_SOURCE).toContain("What this host checked for itself");
    expect(PAGE_SOURCE).toContain("What the bundle reports about itself");
    expect(PAGE_SOURCE).toContain("A claim, not a credential");
    expect(PAGE_SOURCE).toMatch(/verdict that\s*\n?\s*decides/);
  });

  it("uses the host's own class names and adds no stylesheet", () => {
    for (const cls of ["page", "pagehead", "eyebrow", "card", "muted", "mono"]) {
      expect(html, `expected the host class "${cls}"`).toContain(`class="${cls}"`);
    }
    expect(html).not.toContain("<style");
    expect(html).not.toContain("<link");
    expect(PAGE_SOURCE).not.toMatch(/from\s+["'][^"']+\.css["']/);
  });

  it("ships no i18n key — the host's frozen key counts are exact equality", () => {
    // `tests/subapps/i18nSplit.test.ts` asserts `TOTAL_KEYS`, not
    // `toBeGreaterThan`, so one key turns a host test red.
    expect(PAGE_SOURCE).not.toMatch(/\bfrom\s+["'][^"']*i18n["']/);
    expect(PAGE_SOURCE).not.toMatch(/\bt\(["']/);
  });

  it("themes through host CSS variables, with the host's own values as fallbacks", () => {
    // The token so the page follows the console's theme toggle; the literal so
    // it still reads correctly anywhere the stylesheet has not loaded.
    expect(html).toMatch(/var\(--line, #1f2733\)/);
    expect(html).toMatch(/var\(--te, #ff8200\)/);
    expect(html).toMatch(/var\(--bg, #07090d\)/);
  });

  it("offers the bundle textarea and a disabled submit until something is pasted", () => {
    expect(html).toContain("Studio bundle JSON");
    expect(html).toContain("Check this bundle");
    expect(html).toMatch(/<button[^>]*disabled[^>]*>Check this bundle<\/button>/);
  });

  it("shows no verdict, no refusal and no proposal before anything has been asked", () => {
    expect(html).not.toContain("What this host checked for itself");
    expect(html).not.toContain('class="okbox"');
    expect(html).not.toContain('class="errorbox"');
  });
});
